import {db} from './firebase-config.js';
import {collection,getDocs} from 'https://www.gstatic.com/firebasejs/10.13.0/firebase-firestore.js';
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let subscriptions=[],joined=[];
const fmt=v=>{if(!v)return '—';if(v.toDate)return v.toDate().toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'});if(v.seconds)return new Date(v.seconds*1000).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'});return String(v)};
async function read(name){try{const snap=await getDocs(collection(db,name));return snap.docs.map(d=>({id:d.id,...d.data()}));}catch(e){console.warn(name,e);return[]}}
function renderSubs(){const q=($('search').value||'').toLowerCase();const f=$('filter').value;const rows=subscriptions.filter(x=>(x.email||'').toLowerCase().includes(q)).filter(x=>f==='all'||(f==='verified'?x.verified===true:x.verified!==true));$('subscribers').innerHTML=rows.length?rows.map(x=>`<tr><td>${esc(x.email||'Unknown')}</td><td><span class="pill ${x.verified?'green':''}">${x.verified?'Verified':'Pending'}</span></td><td>${esc(fmt(x.createdAt||x.submittedAt||x.timestamp))}</td></tr>`).join(''):'<tr><td colspan="3" class="empty">No matching subscribers.</td></tr>';const verified=subscriptions.filter(x=>x.verified===true).length;const pct=subscriptions.length?Math.round(verified/subscriptions.length*100):0;$('verified-bar').style.width=pct+'%';$('verified-label').textContent=`${verified} verified · ${pct}% of records`}
function renderJoined(){const unique=new Map();joined.forEach(x=>{const email=x.email||x.emailAddress||'';const key=email||x.id;if(!unique.has(key))unique.set(key,x)});const rows=[...unique.values()];$('joined').innerHTML=rows.length?rows.map(x=>`<tr><td>${esc(x.name||x.displayName||'—')}</td><td>${esc(x.email||x.emailAddress||'—')}</td><td><span class="pill">${esc(x.source||'Firebase')}</span></td></tr>`).join(''):'<tr><td colspan="3" class="empty">No user/member records found yet.</td></tr>';$('joined-count').textContent=rows.length}
function renderActivity(){const all=[...subscriptions.map(x=>({label:'Subscription',email:x.email,time:x.createdAt||x.timestamp})),...joined.map(x=>({label:'Joined account',email:x.email,time:x.createdAt||x.timestamp}))].sort((a,b)=>String(b.time?.seconds||b.time||'').localeCompare(String(a.time?.seconds||a.time||''))).slice(0,5);$('activity').innerHTML=all.length?all.map(x=>`<div class="feed-item"><b>${esc(x.label)}</b><span>${esc(x.email||'Record added')}</span><small>${esc(fmt(x.time))}</small></div>`).join(''):'<div class="empty">No activity records yet.</div>'}
async function load(){ $('status').textContent='Refreshing dashboard…';const [subs,users,members,products,reviews]=await Promise.all([read('subscriptions'),read('users'),read('members'),read('products'),read('reviews')]);subscriptions=subs;joined=[...users.map(x=>({...x,source:'users'})),...members.map(x=>({...x,source:'members'}))];$('subscriber-count').textContent=subscriptions.length;$('product-count').textContent=products.length;$('review-count').textContent=reviews.length;renderSubs();renderJoined();renderActivity();$('status').textContent=`Updated ${new Date().toLocaleTimeString('en-IN')}. If a collection is empty, the site may not be saving records there yet.`}
$('search').addEventListener('input',renderSubs);$('filter').addEventListener('change',renderSubs);$('refresh').addEventListener('click',load);load();
