import {db} from './firebase-config.js';
import {collection,getDocs,addDoc,updateDoc,deleteDoc,doc,serverTimestamp,getDoc,setDoc} from 'https://www.gstatic.com/firebasejs/10.13.0/firebase-firestore.js';
const $=id=>document.getElementById(id),status=$('status');let editing=null;
function msg(t,ok=false){status.textContent=t;status.className=ok?'success':'error'}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function tabs(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));$(b.dataset.tab).classList.add('active');if(b.dataset.tab==='reviews')loadReviews();if(b.dataset.tab==='comments')loadComments();if(b.dataset.tab==='site')loadSite()})}tabs();
function reset(){ $('product-form').reset();editing=null;$('cancel').hidden=true}
function productCard(p){const el=document.createElement('div');el.className='row';el.innerHTML=`<div><b>${esc(p.name)}</b><div>${esc(p.price)}</div><small>${esc(p.description)}</small></div><div><button data-edit>Edit</button> <button data-del class="danger">Delete</button></div>`;el.querySelector('[data-edit]').onclick=()=>{editing=p.id;$('name').value=p.name||'';$('price').value=p.price||'';$('image').value=p.image||'';$('description').value=p.description||'';$('cancel').hidden=false;scrollTo(0,0)};el.querySelector('[data-del]').onclick=async()=>{if(confirm('Delete product?')){await deleteDoc(doc(db,'products',p.id));msg('Product deleted',true);loadProducts()}};return el}
async function loadProducts(){try{const s=await getDocs(collection(db,'products'));$('products-list').replaceChildren(...s.docs.map(d=>productCard({id:d.id,...d.data()})));if(!s.size)$('products-list').textContent='No products yet.'}catch(e){msg(e.message)}}
$('product-form').onsubmit=async e=>{e.preventDefault();const p={name:$('name').value.trim(),price:$('price').value.trim(),image:$('image').value.trim(),description:$('description').value.trim(),updatedAt:serverTimestamp()};try{if(editing)await updateDoc(doc(db,'products',editing),p);else await addDoc(collection(db,'products'),{...p,createdAt:serverTimestamp()});msg('Product saved',true);reset();loadProducts()}catch(e){msg(e.message)}};$('cancel').onclick=reset;
async function generic(collectionName,target,label){try{const s=await getDocs(collection(db,collectionName));const out=$(target);out.replaceChildren();if(!s.size){out.textContent='No '+label+' yet.';return}s.forEach(d=>{const x=d.data(),el=document.createElement('div');el.className='row';el.innerHTML=`<div><b>${esc(x.name||x.email||'Customer')}</b><div>${esc(x.text||x.comment||x.content||'')}</div><small>${x.rating?esc(x.rating)+' / 5 stars':''}</small></div><button class="danger">Delete</button>`;el.querySelector('button').onclick=async()=>{if(confirm('Delete this '+label+'?')){await deleteDoc(doc(db,collectionName,d.id));msg(label+' deleted',true);generic(collectionName,target,label)}};out.append(el)})}catch(e){$(target).textContent='Could not load: '+e.message}}
function loadReviews(){generic('reviews','reviews-list','review')}function loadComments(){generic('confessions','comments-list','comment')}
async function loadSite(){try{const s=await getDoc(doc(db,'siteSettings','main'));if(s.exists()){const x=s.data();$('heroTitle').value=x.heroTitle||'';$('heroSubtitle').value=x.heroSubtitle||'';$('announcement').value=x.announcement||''}}catch(e){msg(e.message)}}
$('site-form').onsubmit=async e=>{e.preventDefault();try{await setDoc(doc(db,'siteSettings','main'),{heroTitle:$('heroTitle').value,heroSubtitle:$('heroSubtitle').value,announcement:$('announcement').value,updatedAt:serverTimestamp()},{merge:true});msg('Website text saved',true)}catch(e){msg(e.message)}};loadProducts();
