import {db,auth} from './firebase-config.js';
import {collection,addDoc,query,where,orderBy,onSnapshot,serverTimestamp} from 'https://www.gstatic.com/firebasejs/10.13.0/firebase-firestore.js';
const products={"Blush Ring":{image:'images/product-pink.png',price:0,description:'Handmade pink beaded wall hanging.'},"Azure Ring":{image:'images/product-blue.png',price:0,description:'Handmade blue beaded wall hanging.'},"Ivy Ring":{image:'images/product-green.png',price:0,description:'Handmade green beaded wall hanging.'}};
const name=new URLSearchParams(location.search).get('name')||'Blush Ring',p=products[name]||products['Blush Ring'];
document.getElementById('product-name').textContent=name;document.getElementById('product-image').src=p.image;document.getElementById('product-price').textContent=p.price?'₹'+p.price:'Price coming soon';document.getElementById('product-description').textContent=p.description;
const gallery=document.getElementById('gallery'),img=document.getElementById('product-image');gallery.addEventListener('mousemove',e=>{const r=gallery.getBoundingClientRect();gallery.style.setProperty('--mx',((e.clientX-r.left)/r.width*100)+'%');gallery.style.setProperty('--my',((e.clientY-r.top)/r.height*100)+'%');gallery.classList.add('zoomed')});gallery.addEventListener('mouseleave',()=>gallery.classList.remove('zoomed'));
const cart=()=>JSON.parse(localStorage.getItem('dc-cart')||'[]');document.getElementById('add').onclick=()=>{let c=cart(),q=Math.max(1,+document.getElementById('qty').value||1),x=c.find(i=>i.name===name);if(x)x.qty+=q;else c.push({name,price:p.price,image:p.image,qty:q});localStorage.setItem('dc-cart',JSON.stringify(c));location.href='cart.html';};
const reviews=document.getElementById('reviews'),summary=document.getElementById('rating-summary');const q=query(collection(db,'reviews'),where('product','==',name),orderBy('createdAt','desc'));onSnapshot(q,s=>{let total=0,html='';s.forEach(d=>{const r=d.data();total+=Number(r.rating);html+=`<article class="review"><b>${escapeHtml(r.name)}</b><div class="stars">${'★'.repeat(r.rating)}${'☆'.repeat(5-r.rating)}</div><p>${escapeHtml(r.text)}</p></article>`});reviews.innerHTML=html||'<div class="empty">No reviews yet.</div>';const avg=s.size?total/s.size:0;summary.innerHTML=`${'★'.repeat(Math.round(avg))}${'☆'.repeat(5-Math.round(avg))} <small>(${s.size} ratings)</small>`;},()=>reviews.textContent='Reviews are not available yet. Check Firebase setup.');
function escapeHtml(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
document.getElementById('review-form').onsubmit=async e=>{e.preventDefault();const user=auth.currentUser;if(!user){document.getElementById('status').textContent='Please log in to submit a review.';return;}const rating=Number(document.getElementById('review-rating').value);const text=document.getElementById('review-text').value.trim();if(!rating||rating<1||rating>5||!text)return;await addDoc(collection(db,'reviews'),{product:name,name:document.getElementById('review-name').value.trim(),rating,text,uid:user.uid,createdAt:serverTimestamp()});e.target.reset();document.getElementById('status').textContent='Review submitted.';};
